# Generated by Django 2.2.2 on 2019-10-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191017_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Lorem Ipsum', max_length=900),
        ),
    ]
