# Generated by Django 2.2.2 on 2019-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20191023_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.TextField(blank=True, default='Youtube Video embed code', max_length=900, null=True),
        ),
    ]
