# Generated by Django 2.2.2 on 2019-10-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20191023_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('question', models.TextField(max_length=999)),
                ('level', models.CharField(choices=[('ND-I', 'ND-I'), ('ND-II', 'ND-II'), ('HND-I', 'HND-I'), ('HND-II', 'HND-II')], max_length=50)),
            ],
        ),
    ]
