# Generated by Django 2.2.2 on 2019-10-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
