# Generated by Django 2.2.2 on 2019-10-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_assignment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
