# Generated by Django 2.2.2 on 2019-10-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_assignment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('matric', models.CharField(max_length=50)),
                ('question', models.TextField(max_length=999)),
                ('level', models.CharField(max_length=50)),
                ('answer', models.FileField(upload_to='')),
                ('submitted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
