# Generated by Django 2.2.2 on 2019-10-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answeredBy',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
