# Generated by Django 2.2.2 on 2019-10-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_answer_answeredby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answeredBy',
            new_name='author',
        ),
    ]
